NEWS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/v1/", include("api.urls")),
    path("", include("newspaper.urls")),
    path("news-admin/", include("blog_app.urls")),
    path("accounts/login/", views.LoginView.as_view(), name="login"),
    path("accounts/logout/", views.LogoutView.as_view(), name="logout"),
    path("summernote/", include("django_summernote.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import include, path
from rest_framework import routers

from api import views

router = routers.DefaultRouter()
router.register(r"users", views.UserViewSet)
router.register(r"groups", views.GroupViewSet)
router.register(r"posts", views.PostViewSet)


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path("", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

urlpatterns += router.urls
urlpatterns += [
    path(
        "post/<int:post_id>/comments/",
        views.CommentViewSet.as_view(),
        name="comment-api",
    ),
]

blog_app/urls.py
from django.urls import path

from blog_app import views

app_name = "news_admin"

# {% url 'news_admin:post-list' %}

urlpatterns = [
    path(
        "",
        views.PostListView.as_view(),
        name="post-list",
    ),
    path(
        "post-detail/<int:pk>/",
        views.PostDetailView.as_view(),
        name="post-detail",
    ),
    path(
        "draft-list/",
        views.DraftListView.as_view(),
        name="draft-list",
    ),
    path(
        "draft-detail/<int:pk>/",
        views.DraftDetailView.as_view(),
        name="draft-detail",
    ),
    path(
        "draft-publish/<int:pk>/",
        views.DraftPublishView.as_view(),
        name="draft-publish",
    ),
    path(
        "post-delete/<int:pk>/",
        views.PostDeleteView.as_view(),
        name="post-delete",
    ),
    path(
        "post-create/",
        views.PostCreateView.as_view(),
        name="post-create",
    ),
    path(
        "post-update/<int:pk>/",
        views.PostUpdateView.as_view(),
        name="post-update",
    ),
    path(
        "tag-list/",
        views.TagListView.as_view(),
        name="tag-list",
    ),
    path(
        "category-list/",
        views.CategoryListView.as_view(),
        name="category-list",
    ),
    path(
        "post-list/",
        views.AllPostListView.as_view(),
        name="all-post-list",
    ),
    path(
        "tag-create/",
        views.TagCreateView.as_view(),
        name="tag-create",
    ),
    path(
        "tag-update/<int:pk>/",
        views.TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tag-delete/<int:pk>/",
        views.TagDeleteView.as_view(),
        name="tag-delete",
    ),
    path(
        "category-create/",
        views.CategoryCreateView.as_view(),
        name="category-create",
    ),
    path(
        "category-update/<int:pk>/",
        views.CategoryUpdateView.as_view(),
        name="category-update",
    ),
    path(
        "category-delete/<int:pk>/",
        views.CategoryDeleteView.as_view(),
        name="category-delete",
    ),
]

templates/admin_lte/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>AdminLTE 3 | Dashboard</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback" />
    <!-- Font Awesome -->
    <link rel="stylesheet"
          href="{% static 'admin-lte/plugins/fontawesome-free/css/all.min.css' %}" />
    <!-- Ionicons -->
    <link rel="stylesheet"
          href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %}" />
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet"
          href="{% static 'admin-lte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}" />
    <!-- iCheck -->
    <link rel="stylesheet"
          href="{% static 'admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}" />
    <!-- JQVMap -->
    <link rel="stylesheet"
          href="{% static 'admin-lte/plugins/jqvmap/jqvmap.min.css' %}" />
    <!-- Theme style -->
    <link rel="stylesheet"
          href="{% static 'admin-lte/dist/css/adminlte.min.css' %}" />
    <!-- overlayScrollbars -->
    <link rel="stylesheet"
          href="{% static 'admin-lte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}" />
    <!-- Daterange picker -->
    <link rel="stylesheet"
          href="{% static 'admin-lte/plugins/daterangepicker/daterangepicker.css' %}" />
    <!-- summernote -->
    <link rel="stylesheet"
          href="{% static 'admin-lte/plugins/summernote/summernote-bs4.min.css' %}" />

    {% block extra_css %}
 
    {% endblock extra_css %}
  </head>
  <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

      {% include "admin_lte/partials/preloader.html" %}
      {% include "admin_lte/partials/navbar.html" %}
      {% include "admin_lte/partials/sidebar.html" %}

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        {% include "admin_lte/partials/breadcrumb.html" %}
        <!-- Main content -->
        <section class="content">
          <div class="container-fluid">
            {% block content %}
 
            {% endblock content %}
          </div>
          <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->
      <footer class="main-footer">
        <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
          <b>Version</b> 3.2.0
        </div>
      </footer>

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
      </aside>
      <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    <!-- jQuery -->
    <script src="{% static 'admin-lte/plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'admin-lte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- ChartJS -->
    <script src="{% static 'admin-lte/plugins/chart.js/Chart.min.js' %}"></script>
    <!-- Sparkline -->
    <script src="{% static 'admin-lte/plugins/sparklines/sparkline.js' %}"></script>
    <!-- JQVMap -->
    <script src="{% static 'admin-lte/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
    <script src="{% static 'admin-lte/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{% static 'admin-lte/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
    <!-- daterangepicker -->
    <script src="{% static 'admin-lte/plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'admin-lte/plugins/daterangepicker/daterangepicker.js' %}"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{% static 'admin-lte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- Summernote -->
    <script src="{% static 'admin-lte/plugins/summernote/summernote-bs4.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{% static 'admin-lte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'admin-lte/dist/js/adminlte.js' %}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'admin-lte/dist/js/pages/dashboard.js' %}"></script>

    {% block extra_js %}
 
    {% endblock extra_js %}
  </body>
</html>

templates/admin_lte/post_create.html
{% extends "admin_lte/base.html" %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <form action=""
            method="post"
            class="post-form"
            enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Save</button>
      </form>
    </div>
  </div>
{% endblock content %}

templates/admin_lte/post_list.html
{% extends "admin_lte/base.html" %}
{% load static %}

{% block extra_css %}
  <!-- DataTables -->
  <link rel="stylesheet"
        href="{% static 'admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}" />
  <link rel="stylesheet"
        href="{% static 'admin-lte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}" />
  <link rel="stylesheet"
        href="{% static 'admin-lte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}" />
{% endblock extra_css %}

{% block content %}
  <!-- Small boxes (Stat box) -->
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">DataTable with default features</h3>
          <div class="float-right">
            <a href="{% url 'news_admin:post-create' %}" class="btn btn-primary">Add</a>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>Name</th>
                <th>Is Published</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {% for post in posts %}
                <tr>
                  <td>{{ post.title }}</td>
                  <td>
                    {% if post.published_at %}
                      <a href="" class="btn btn-primary disabled">Publish</a>
                    {% else %}
                      <a href="{% url 'news_admin:draft-publish' post.pk %}" class="btn btn-primary">Publish</a>
                    {% endif %}
                  </td>
                  <td>
                    <a href="{% url 'news_admin:post-update' post.pk %}"
                       class="btn btn-success">Update</a>
                    {% if post.published_at %}
                      <a href="{% url 'news_admin:post-detail' post.pk %}"
                         class="btn btn-primary">View</a>
                    {% else %}
                      <a href="{% url 'news_admin:draft-detail' post.pk %}"
                         class="btn btn-primary">View</a>
                    {% endif %}
                    <a href="{% url 'news_admin:post-delete' post.pk %}"
                       class="btn btn-danger">Delete</a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
            <tfoot>
              <tr>
                <th>Name</th>
                <th>Is Published</th>
                <th>Action</th>
              </tr>
            </tfoot>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
    </div>
  </div>
{% endblock content %}

{% block extra_js %}
  <!-- DataTables  & Plugins -->
  <script src="{% static 'admin-lte/plugins/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/jszip/jszip.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/pdfmake/pdfmake.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/pdfmake/vfs_fonts.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
  <script>
      $(function() {

          $('#example1').DataTable({

          });
      });
  </script>
{% endblock extra_js %}

templates/admin_lte/tag_list.html
{% extends "admin_lte/base.html" %}
{% load static %}

{% block extra_css %}
  <link rel="stylesheet"
        href="{% static 'admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}" />
  <link rel="stylesheet"
        href="{% static 'admin-lte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}" />
  <link rel="stylesheet"
        href="{% static 'admin-lte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}" />
{% endblock extra_css %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Tags</h3>
          <div class="float-right">
            <a href="{% url 'news_admin:tag-create' %}" class="btn btn-primary">Add</a>
          </div>
        </div>
 
        <!-- /.card-header -->
        <div class="card-body">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>Name</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {% for tag in tags %}
                <tr>
                  <td>{{ tag.name }}</td>
                  <td>
                    <a href="{% url 'news_admin:tag-update' tag.pk %}"
                       class="btn btn-success">Update</a>
                    <a href="{% url 'news_admin:tag-delete' tag.pk %}"
                       class="btn btn-danger">Delete</a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
            <tfoot>
              <tr>
                <th>Name</th>
                <th>Action</th>
              </tr>
            </tfoot>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
    <!-- /.col -->
  </div>
{% endblock content %}

{% block extra_js %}

  <!-- DataTables  & Plugins -->
  <script src="{% static 'admin-lte/plugins/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/jszip/jszip.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/pdfmake/pdfmake.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/pdfmake/vfs_fonts.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
  <script src="{% static 'admin-lte/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
  <script src="{% static 'admin-lte/dist/js/adminlte.min.js' %}"></script>

  <script>
      console.log("helo")
      $('#example1').DataTable({

      });
  </script>

{% endblock extra_js %}